version: '2.0'
services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      all:
        ipv4_address: 172.16.238.6
    logging:
      options:
        max-file: "5"
        max-size: 10m
  db:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: compose
    networks:
      all:
        ipv4_address: 172.16.238.7
    logging:
      options:
        max-file: "5"
        max-size: 10m
  redis:
    image: redis:5.0.10
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      all:
        ipv4_address: 172.16.238.8
    logging:
      options:
        max-file: "5"
        max-size: 10m
  segmently_django:
    build: ./segmently_django
    restart: always
    command: >
      bash -c "chmod a+x ./run.sh
      && ./run.sh"
    ports:
      - 8000:8000
    environment:
      DOCKER: docker
    depends_on:
      - db
    networks:
      all:
        ipv4_address: 172.16.238.2
    logging:
      options:
        max-file: "5"
        max-size: 10m
  segmently_dashboard:
    build: ./segmently_dashboard
    restart: always
    ports:
      - 8080:80
    networks:
      all:
        ipv4_address: 172.16.238.5
    logging:
      options:
        max-file: "5"
        max-size: 10m
volumes:
  mongodb_data:
  mongodb_config:
networks:
  all:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24