# Generated by Django 2.2.3 on 2022-05-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_notes', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('segment', models.CharField(max_length=200)),
                ('config_input_data', models.TextField(blank=True, null=True)),
                ('analytics_output_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddIndex(
            model_name='buildconfig',
            index=models.Index(fields=['name'], name='build_confi_name_f81f17_idx'),
        ),
        migrations.AddIndex(
            model_name='buildconfig',
            index=models.Index(fields=['-name'], name='build_confi_name_b5ee4e_idx'),
        ),
    ]
