# Generated by Django 2.2.3 on 2022-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildconfig',
            name='status',
            field=models.CharField(blank=True, choices=[('QUEUED', 'QUEUED'), ('EXECUTING', 'EXECUTING'), ('PROCESSED', 'PROCESSED')], default='QUEUED', max_length=200, null=True),
        ),
    ]
