# Generated by Django 2.2.3 on 2022-05-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverInsights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_notes', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('segment', models.CharField(max_length=200)),
                ('kpi_data', models.TextField(blank=True, null=True)),
                ('graph_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='discoverinsights',
            index=models.Index(fields=['segment'], name='discover_in_segment_7f1b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='discoverinsights',
            index=models.Index(fields=['-segment'], name='discover_in_segment_92cd41_idx'),
        ),
    ]
